chore: rename pipeline

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: Terraform Plan Test
+name: build
 
 on:
   push:
@@ -21,7 +21,7 @@ jobs:
       GITHUB_APP_INSTALLATION_ID: "74918728"
       GITHUB_APP_PEM_FILE: ${{ secrets.GH_APP_PEM_FILE }}
 
-  verify:
+  verify-plan:
     runs-on: ubuntu-latest
     needs: plan
     steps:
@@ -33,3 +33,28 @@ jobs:
         fi
         echo "Terraform plan succeeded."
         echo "${{ needs.plan.outputs.plan_output }}"
+
+  apply:
+    uses: ./.github/workflows/terraform-apply.yml
+    with:
+      directory: ./test/terraform
+      terraform_version: '1.12.2'
+    secrets:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      GITHUB_APP_ID: "1552622"
+      GITHUB_APP_INSTALLATION_ID: "74918728"
+      GITHUB_APP_PEM_FILE: ${{ secrets.GH_APP_PEM_FILE }}
+
+  verify-apply:
+    runs-on: ubuntu-latest
+    needs: apply
+    steps:
+    - name: Verify Terraform Apply
+      run: |
+        if [ "${{ needs.apply.outputs.apply_outcome }}" != "success" ]; then
+          echo "Terraform apply failed."
+          exit 1
+        fi
+        echo "Terraform apply succeeded."
+        echo "${{ needs.apply.outputs.apply_output }}"
